services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: Filo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: filo-api:local
    build:
      context: .
      dockerfile: src/filo.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AppVersion: local-compose
      ConnectionStrings__Database: Host=postgres;Port=5432;Database=Filo;Username=postgres;Password=postgres
      Auth0__Domain: filo-dev.eu.auth0.com
      Auth0__ManagementClientId: ${AUTH0_MGMT_CLIENT_ID:-6kCmhrNW6AEM0sucweFQr1lbTaNySMYm}
      Auth0__ManagementClientSecret: ${AUTH0_MGMT_SECRET:-rjG7fUy3-eEJLg_52r61TM8f2VJ6i2MKQc2acOrXE8tr6Cqf3Yas914EH9yKbz2V}
      Auth0__BffClientId: ${AUTH0_BFF_CLIENT_ID:-cNAIHuKup6VZE6tnGlocvz15X56aVGfo}
      Auth0__BffClientSecret: ${AUTH0_BFF_SECRET:-9vhKpMfGD_UM7Ba_QHtG1f_9RV1Xb0xgskEy99x-qULCeoed0-DVjoStghVTyMML}
      Auth0__Audience: https://api.filo.dev
      Email__SmtpHost: host
      Email__SmtpPort: 587
      Email__FromAddress: something@gmail.com
    ports:
      - "5005:8080"
    depends_on:
      postgres:
        condition: service_healthy

  spa:
    image: filo-ui:local
    build:
      context: .
      dockerfile: src/Filo.Ui/Dockerfile
    environment:
      BFF_UPSTREAM: http://api:8080
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  postgres-data:
