import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc8fb',
          400: '#36aaf5',
          500: '#0c8ee7',
          600: '#0070c4',
          700: '#01599f',
          800: '#064c83',
          900: '#0b406d',
          950: '#07284a',
        },
        primary: '#17171c',
        'cohere-black': '#000000',
        ink: '#212121',
        'deep-green': '#003c33',
        'dark-navy': '#071829',
        canvas: '#ffffff',
        'soft-stone': '#eeece7',
        'pale-green': '#edfce9',
        'pale-blue': '#f1f5ff',
        hairline: '#d9d9dd',
        'border-light': '#e5e7eb',
        'card-border': '#f2f2f2',
        muted: '#93939f',
        slate: '#75758a',
        'body-muted': '#616161',
        'action-blue': '#1863dc',
        'focus-blue': '#4c6ee6',
        coral: '#ff7759',
        'coral-soft': '#ffad9b',
        'form-focus': '#9b60aa',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        error: '#b30000',
      },
      fontFamily: {
        sans: ['Unica77 Cohere Web', 'Inter', 'Arial', 'ui-sans-serif', 'system-ui'],
        display: ['CohereText', 'Space Grotesk', 'ui-sans-serif', 'system-ui'],
        body: ['Unica77 Cohere Web', 'Inter', 'Arial', 'ui-sans-serif', 'system-ui'],
        mono: ['CohereMono', 'Arial', 'ui-sans-serif', 'system-ui'],
      },
      fontSize: {
        'hero-display': ['96px', { lineHeight: '1', letterSpacing: '-1.92px', fontWeight: '400' }],
        'product-display': ['72px', { lineHeight: '1', letterSpacing: '-1.44px', fontWeight: '400' }],
        'section-display': ['60px', { lineHeight: '1', letterSpacing: '-1.2px', fontWeight: '400' }],
        'section-heading': ['48px', { lineHeight: '1.2', letterSpacing: '-0.48px', fontWeight: '400' }],
        'card-heading': ['32px', { lineHeight: '1.2', letterSpacing: '-0.32px', fontWeight: '400' }],
        'feature-heading': ['24px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '400' }],
        'body-large': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        body: ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        button: ['14px', { lineHeight: '1.71', letterSpacing: '0', fontWeight: '500' }],
        caption: ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'mono-label': ['14px', { lineHeight: '1.4', letterSpacing: '0.28px', fontWeight: '400' }],
        micro: ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '22px',
        xl: '30px',
        pill: '32px',
      },
      spacing: {
        xxs: '2px',
        xs: '6px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        section: '80px',
      },
      keyframes: {
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.4s ease-out both',
        'fade-in': 'fade-in 0.5s ease-out both',
        'gradient-shift': 'gradient-shift 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

export default config
