// <auto-generated />
using System;
using System.Collections.Generic;
using Filo.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Filo.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611131922_CreateUsersRolesPermissions")]
    partial class CreateUsersRolesPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Filo")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Filo.Domain.Entities.DummyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("DummyItems", "Filo");
                });

            modelBuilder.Entity("Filo.Domain.Users.Permissions", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("Permissions", "Filo");

                    b.HasData(
                        new
                        {
                            Code = "space:create"
                        },
                        new
                        {
                            Code = "space:read.all"
                        },
                        new
                        {
                            Code = "space:read"
                        },
                        new
                        {
                            Code = "file:download"
                        },
                        new
                        {
                            Code = "file:upload"
                        });
                });

            modelBuilder.Entity("Filo.Domain.Users.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Name");

                    b.ToTable("Roles", "Filo");

                    b.HasData(
                        new
                        {
                            Name = "Administrator"
                        },
                        new
                        {
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("Filo.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Filo.Domain.Users.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "Filo.Domain.Users.User.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Users", "Filo");
                });

            modelBuilder.Entity("PermissionsRole", b =>
                {
                    b.Property<string>("PermissionsCode")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)");

                    b.HasKey("PermissionsCode", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("RolePermissions", "Filo");

                    b.HasData(
                        new
                        {
                            PermissionsCode = "space:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionsCode = "space:read.all",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionsCode = "space:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionsCode = "file:upload",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionsCode = "file:download",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionsCode = "space:create",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionsCode = "space:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionsCode = "file:upload",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionsCode = "file:download",
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesName", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "Filo");
                });

            modelBuilder.Entity("PermissionsRole", b =>
                {
                    b.HasOne("Filo.Domain.Users.Permissions", null)
                        .WithMany()
                        .HasForeignKey("PermissionsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filo.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Filo.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
